spring.application.name=utility-billing-system
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/utility_billing_db
spring.datasource.username=postgres
spring.datasource.password=lucky
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.mapper.accept-case-insensitive-enums=true

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

jwt.secret=change-this-secret-key-to-a-secure-minimum-32-char-value
jwt.expiration=86400000

app.seed.enabled=true
app.billing.due-days=15
app.reading.max-consumption=1000000
app.db.routines.auto-apply=true
app.mail.enabled=true
app.auth.otp.expiry-minutes=10

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kagabolucky72@gmail.com
spring.mail.password=psav fqgq zdyy hqjb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha